[2024-03-13T06:40:19.547+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:19.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:40:19.549+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:40:19.549+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:19.561+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:40:19.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:40:19.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:19.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T06:40:49.934+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:49.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:40:49.936+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:40:49.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:49.947+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:40:49.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:40:49.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:40:49.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T06:41:20.423+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:20.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:41:20.424+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:41:20.424+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:20.436+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:41:20.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:41:20.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:20.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.034 seconds
[2024-03-13T06:41:50.991+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:50.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:41:50.993+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:41:50.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:51.010+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:41:51.007+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:41:51.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:41:51.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.042 seconds
[2024-03-13T06:42:21.389+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:21.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:42:21.391+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:42:21.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:21.400+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:42:21.398+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:42:21.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:21.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
[2024-03-13T06:42:51.663+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:51.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:42:51.664+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:42:51.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:51.677+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:42:51.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:42:51.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:42:51.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.034 seconds
[2024-03-13T06:43:21.985+0000] {processor.py:161} INFO - Started process (PID=770) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:21.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:43:21.987+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:43:21.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:22.004+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:43:22.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:43:22.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:22.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.038 seconds
[2024-03-13T06:43:52.419+0000] {processor.py:161} INFO - Started process (PID=826) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:52.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:43:52.421+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:43:52.421+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:52.431+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:43:52.429+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:43:52.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:43:52.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.030 seconds
[2024-03-13T06:44:22.837+0000] {processor.py:161} INFO - Started process (PID=882) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:22.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:44:22.839+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:44:22.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:22.849+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:44:22.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:44:22.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:22.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.030 seconds
[2024-03-13T06:44:53.117+0000] {processor.py:161} INFO - Started process (PID=938) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:53.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:44:53.119+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:44:53.119+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:53.141+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:44:53.134+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:44:53.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:44:53.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-03-13T06:45:23.229+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:23.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:45:23.231+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:45:23.231+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:23.244+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:45:23.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:45:23.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:23.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T06:45:53.817+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:53.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:45:53.820+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:45:53.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:53.835+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:45:53.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:45:53.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:45:53.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.038 seconds
[2024-03-13T06:46:24.417+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:24.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:46:24.419+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:46:24.419+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:24.437+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:46:24.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:46:24.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:24.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.041 seconds
[2024-03-13T06:46:54.805+0000] {processor.py:161} INFO - Started process (PID=1170) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:54.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:46:54.807+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:46:54.806+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:54.819+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:46:54.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:46:54.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:46:54.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T06:47:25.093+0000] {processor.py:161} INFO - Started process (PID=1226) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:25.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:47:25.096+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:47:25.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:25.114+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:47:25.111+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:47:25.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:25.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-03-13T06:47:55.229+0000] {processor.py:161} INFO - Started process (PID=1282) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:55.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:47:55.231+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:47:55.231+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:55.242+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:47:55.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:47:55.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:47:55.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T06:48:25.621+0000] {processor.py:161} INFO - Started process (PID=1338) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:25.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:48:25.623+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:48:25.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:25.637+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:48:25.634+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:48:25.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:25.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.037 seconds
[2024-03-13T06:48:55.919+0000] {processor.py:161} INFO - Started process (PID=1396) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:55.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:48:55.920+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:48:55.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:55.933+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:48:55.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:48:55.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:48:55.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T06:49:26.199+0000] {processor.py:161} INFO - Started process (PID=1452) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:26.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:49:26.202+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:49:26.201+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:26.215+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:49:26.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:49:26.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:26.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T06:49:56.405+0000] {processor.py:161} INFO - Started process (PID=1510) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:56.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:49:56.407+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:49:56.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:56.421+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:49:56.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:49:56.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:49:56.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T06:50:26.587+0000] {processor.py:161} INFO - Started process (PID=1566) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:26.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:50:26.589+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:50:26.589+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:26.601+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:50:26.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:50:26.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:26.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
[2024-03-13T06:50:56.798+0000] {processor.py:161} INFO - Started process (PID=1626) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:56.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:50:56.800+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:50:56.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:56.812+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:50:56.809+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:50:56.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:50:56.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
[2024-03-13T06:51:27.172+0000] {processor.py:161} INFO - Started process (PID=1685) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:51:27.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:51:27.174+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:51:27.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:51:27.184+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:51:27.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:51:27.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:51:27.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
[2024-03-13T06:52:18.459+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:18.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:52:18.461+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:52:18.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:18.475+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:52:18.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:52:18.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:18.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.040 seconds
[2024-03-13T06:52:48.858+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:48.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:52:48.861+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:52:48.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:48.873+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:52:48.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:52:48.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:52:48.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T06:53:19.584+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:19.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:53:19.586+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:53:19.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:19.601+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:53:19.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:53:19.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:19.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.039 seconds
[2024-03-13T06:53:50.030+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:50.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:53:50.032+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:53:50.032+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:50.047+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:53:50.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:53:50.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:53:50.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.038 seconds
[2024-03-13T06:54:20.526+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:20.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:54:20.528+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:54:20.528+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:20.540+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:54:20.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:54:20.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:20.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.034 seconds
[2024-03-13T06:54:50.661+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:50.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:54:50.665+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:54:50.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:50.688+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:54:50.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:54:50.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:54:50.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.055 seconds
[2024-03-13T06:55:21.579+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:21.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:55:21.582+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:55:21.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:21.600+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:55:21.596+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T06:55:21.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:21.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-03-13T06:55:52.420+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:52.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:55:52.423+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:55:52.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:52.647+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:55:52.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2024-03-13T06:55:52.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:55:52.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.247 seconds
[2024-03-13T06:56:23.279+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T06:56:23.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T06:56:23.281+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:56:23.281+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:56:23.488+0000] {logging_mixin.py:188} INFO - [2024-03-13T06:56:23.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2024-03-13T06:56:23.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T06:56:23.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.226 seconds
[2024-03-13T07:02:11.696+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:11.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:02:11.699+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:02:11.699+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:11.715+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:02:11.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:02:11.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:11.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-03-13T07:02:42.461+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:42.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:02:42.465+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:02:42.464+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:42.482+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:02:42.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:02:42.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:02:42.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.058 seconds
[2024-03-13T07:03:13.169+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:13.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:03:13.171+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:03:13.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:13.183+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:03:13.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:03:13.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:13.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.034 seconds
[2024-03-13T07:03:43.584+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:43.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:03:43.586+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:03:43.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:43.597+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:03:43.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:03:43.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:03:43.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.030 seconds
[2024-03-13T07:04:14.003+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:14.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:04:14.006+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:04:14.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:14.019+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:04:14.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:04:14.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:14.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T07:04:44.658+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:44.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:04:44.661+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:04:44.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:44.672+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:04:44.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:04:44.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:04:44.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.032 seconds
[2024-03-13T07:05:14.955+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:14.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:05:14.958+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:05:14.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:14.969+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:05:14.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:05:14.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:14.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.035 seconds
[2024-03-13T07:05:45.307+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:45.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:05:45.310+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:05:45.309+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:45.320+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:05:45.317+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:05:45.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:05:45.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
[2024-03-13T07:06:15.645+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:15.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:06:15.648+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:06:15.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:15.658+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:06:15.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:06:15.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:15.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T07:06:46.083+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:46.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:06:46.085+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:06:46.085+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:46.095+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:06:46.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:06:46.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:06:46.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T07:07:16.476+0000] {processor.py:161} INFO - Started process (PID=603) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:07:16.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:07:16.479+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:07:16.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:07:16.492+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:07:16.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:07:16.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:07:16.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.040 seconds
[2024-03-13T07:09:29.301+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:29.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:09:29.304+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:09:29.304+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:29.318+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:09:29.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:09:29.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:29.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.039 seconds
[2024-03-13T07:09:59.438+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:59.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:09:59.440+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:09:59.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:59.449+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:09:59.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:09:59.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:09:59.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.029 seconds
[2024-03-13T07:10:29.599+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:29.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:10:29.602+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:10:29.602+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:29.612+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:10:29.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:10:29.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:29.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.033 seconds
[2024-03-13T07:10:59.917+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:59.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:10:59.920+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:10:59.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:59.929+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:10:59.927+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:10:59.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:10:59.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.030 seconds
[2024-03-13T07:11:30.195+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/hw_dag.py
[2024-03-13T07:11:30.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-03-13T07:11:30.197+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:11:30.197+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:11:30.207+0000] {logging_mixin.py:188} INFO - [2024-03-13T07:11:30.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 15, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-03-13T07:11:30.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-03-13T07:11:30.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.031 seconds
